apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: py-app
        image: vinayjadhav/reddit-clone-app:replaceImageTag
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: svc-py-app
  namespace: python
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: py
  type: LoadBalancer





